import { AppState } from "../types";

export const defaultAppState: AppState = {
  categories: [
    {
      id: "mains",
      nameEn: "Signature Mains",
      nameAr: "الأطباق الرئيسية والأصيلة",
      nameOm: "Nyaata Filatamo",
      nameAm: "ልዩ ምግቦች",
      icon: "Beef"
    },
    {
      id: "appetizers",
      nameEn: "Golden Appetizers",
      nameAr: "المقبلات الذهبية والمقرمشة",
      nameOm: "Nyaata Salphaa",
      nameAm: "መክሰስ",
      icon: "Utensils"
    },
    {
      id: "desserts",
      nameEn: "Sweet Indulgences",
      nameAr: "الحلويات الفاخرة",
      nameOm: "Mi'aawaa",
      nameAm: "ጣፋጭ ምግቦች",
      icon: "Cake"
    },
    {
      id: "beverages",
      nameEn: "Refreshing Drinks",
      nameAr: "مشروبات منعشة ودافئة",
      nameOm: "Dhugaatii",
      nameAm: "መጠጦች",
      icon: "Coffee"
    },
    {
      id: "soft-drinks",
      nameEn: "Soft Drinks",
      nameAr: "المشروبات الغازية والباردة",
      nameOm: "Dhugaatii Lallaafaa",
      nameAm: "ለስلاሳ መጠጦች",
      icon: "TrendingUp"
    },
    {
      id: "rice",
      nameEn: "Aromatic Rice",
      nameAr: "أطباق الأرز العطرة",
      nameOm: "Nyaata Ruuzii",
      nameAm: "የሩዝ ምግቦች",
      icon: "Columns"
    },
    {
      id: "special-mandi",
      nameEn: "Special Mandi",
      nameAr: "المندي الخاص المتميز",
      nameOm: "Mandi Addaa",
      nameAm: "ልዩ ማንዲ",
      icon: "Award"
    },
    {
      id: "other-foods",
      nameEn: "Other Foods",
      nameAr: "مأكولات متنوعة أخرى",
      nameOm: "Nyaatawwan Biroo",
      nameAm: "ሌሎች ምግቦች",
      icon: "Layers"
    }
  ],
  products: [
    {
      id: "prod-1",
      nameEn: "Taqwa Royale Mandi",
      nameAr: "أرز مندي الملكي باللحم",
      nameOm: "Mandi Royale",
      nameAm: "ተቅዋ የላቀ ማንዲ",
      descriptionEn: "Fragrant seasoned rice cooked under hickory wood, served with melt-in-the-mouth roasted lamb, toasted almonds, golden raisins, and dynamic house salsa.",
      descriptionAr: "أرز ذو نكهة عطرة مطبوخ تحت خشب الجوز، يقدم مع لحم ضأن مشوي يذوب في الفم، ولوز محمص، وزبيب ذهبي، وصلصة منزلية حيوية.",
      descriptionOm: "Basmatii urgaahu nuffee mukaan bilchaate, foon hoolaa lallaafaa, boddee fi salsa saxamaa waliin dhiyaata.",
      descriptionAm: "በሚያምር መዓዛ የተቀመመ የተጠበሰ የበግ ስጋ፣ ለውዝ፣ ዘቢብ እና ልዩ ሰልሳ ጋር የሚቀርብ ምርጥ ባህላዊ ማንዲ።",
      price: 1800,
      categoryId: "mains",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-2",
      nameEn: "Flame-Grilled Shish Kabab",
      nameAr: "كباب لحم مشوي على الفحم",
      nameOm: "Kabaab Gilaalame",
      nameAm: "በከሰል የተጠበሰ ሽሽ ካባብ",
      descriptionEn: "Three skewers of succulent beef strip-loin marinated in Taqwa's signature spices, grilled over open coals with roasted peppers and onions.",
      descriptionAr: "ثلاثة أسياخ من اللحم اللذيذ المتبل ببهارات تقوى الخاصة، مشوي على الجمر المفتوح مع الفلفل والبصل المشوي.",
      descriptionOm: "Shish kabaab foon sa'aa cuunfaan addaa kootiin laaffate, koshomii fi burtukaana wajjiin gubbaa dhumarratti qophaaye.",
      descriptionAm: "በተቅዋ ልዩ ቅመማ ቅመም የተቀመመ፣ በከሰል እሳት ላይ ከቃሪያና ሽንኩርት ጋር የሚጠበስ ሶስት ሲክ ምርጥ የበሬ ስጋ።",
      price: 1450,
      categoryId: "mains",
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-3",
      nameEn: "Savoury Gourmet Sambusa",
      nameAr: "سمبوسة مقرمشة متميزة",
      nameOm: "Sambusaa Taqwa",
      nameAm: "ጥራት ያለው ሳምቡሳ",
      descriptionEn: "Crisp golden pastry skins loaded with spiced organic minced beef, fresh coriander, green onions, and mild green chillies.",
      descriptionAr: "عجينة مقرمشة ذهبية محشوة بلحم بقري مفروم متبل، كزبرة طازجة، بصل أخضر وفلفل حار خفيف.",
      descriptionOm: "Sambusaa mi'aawaa foon laafaa mi'eessaan, shunkurtaa dhangalaa'aa wajjiin.",
      descriptionAm: "በቅመማ ቅመም፣ በሽንኩርትና በቃሪያ የተቀመመ የበሬ ስጋ የያዘ ወርቃማና ተወዳጅ ሳምቡሳ።",
      price: 380,
      categoryId: "appetizers",
      image: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&auto=format&fit=crop&q=80",
      isAvailable: true,
      isFeatured: false
    },
    {
      id: "prod-5",
      nameEn: "Pistachio Honey Baklava Royale",
      nameAr: "بقلاوة ملكية بالفستق والعسل",
      nameOm: "Baklavaa Dammaa",
      nameAm: "በፒስታቺዮ እና ማር የተዘጋጀ ባቅላቫ",
      descriptionEn: "Delicate layers of crisp, butter-baked phyllo pastry stuffed with crushed high-grade pistachios and steeped in cardamom-infused local honey.",
      descriptionAr: "طبقات رقيقة من فطيرة الفيلو المخبوزة بالزبدة، محشوة بالفستق المطحون عالي الجودة والمغموسة في عسل محلي معطر بالهيل.",
      descriptionOm: "Baklavaa killiingii dammaa fi pistashiyoo baay'ee mi'aawaa.",
      descriptionAm: "በቅቤና በፒስታቺዮ ተሞልቶ በሻሸመኔ ማር የተነከረ ምርጥ ጣፋጭ ባቅላቫ።",
      price: 650,
      categoryId: "desserts",
      image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&auto=format&fit=crop&q=80",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-6",
      nameEn: "Taqwa Shashemene Espresso Macchiato",
      nameAr: "ماكياتو شاشامان المتميز",
      nameOm: "Espresso Machiyaatoo",
      nameAm: "የተቅዋ ሻሸመኔ ማኪያቶ",
      descriptionEn: "Shashemene's premium sun-dried Arabica coffee, slow-roasted, freshly ground, double shot of espresso topped with silky steamed milk microfoam.",
      descriptionAr: "حبوب بن أرابيكا الممتازة المجففة بالشمس من شاشامان، محمصة ببطء، مطحونة طازجة، كحول مزدوج من إسبريسو تعلوها رغوة حليب ناعمة.",
      descriptionOm: "Buna oomisha Shashamanee beekamaa ta'e irraa qophaaye.",
      descriptionAm: "በአካባቢው ከሚመረት ጥራት ያለው ቡና የሚዘጋጅ፣ ጣፋጭ ወተት የተጨመረበት ማኪያቶ።",
      price: 190,
      categoryId: "beverages",
      image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&auto=format&fit=crop&q=80",
      isAvailable: true,
      isFeatured: false
    },
    {
      id: "prod-sd-1",
      nameEn: "Premium Hibiscus Cool",
      nameAr: "عصير الكركديه المنعش والبارد",
      nameOm: "Hibiscus Cool",
      nameAm: "ልዩ የከርከዴ መጠጥ",
      descriptionEn: "Infused with organic wild berries, fresh hand-picked mint leaves, and sweet lime.",
      descriptionAr: "مغمر بنكهة التوت البري العضوي، وأوراق النعناع الطازجة المنتقاة وبلمسة ليمون حلوة.",
      descriptionOm: "Dhugaatii qabbaneessaa hibiscus berris fi mintii haaraa irraa qophaaye.",
      descriptionAm: "ከበረዶ፣ ከፓሽን ፍሩትና ከልዩ ቅጠላ ቅጠል ጋር ተዋህዶ ቀዝቃዛ የሚቀርብ ተወዳጅ የከርከዴ መጠጥ።",
      price: 180,
      categoryId: "soft-drinks",
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-rc-1",
      nameEn: "Saffron Royal Biryani",
      nameAr: "أرز برياني الزعفران الملكي",
      nameOm: "Ruuzii Biryaanii",
      nameAm: "የሳፍሮን ሮያል ቢሪያኒ",
      descriptionEn: "Premium saffron-infused long grain Basmati steamed with fresh cardamoms, cinnamon barks and cloves.",
      descriptionAr: "أرز بسمتي فاخر طويل الحبة بنكهة الزعفران، مطهو ببطء مع الهيل الطازج وعيدان القرفة والقرنفل العطري.",
      descriptionOm: "Basmatii safroonii fi mi'eessituuwwan aadaa kootiin bilchaate.",
      descriptionAm: "በሚያምር መዓዛና በቅመማ ቅመም የተቀመመ፣ ከሳፍሮን ጋር ተቀላቅሎ የሚዘጋጅ የላቀ ረዥም የሩዝ ምግብ።",
      price: 950,
      categoryId: "rice",
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-sm-1",
      nameEn: "Signature Taqwa Family Mandi",
      nameAr: "مندي عائلي فاخر خاص",
      nameOm: "Taqwa Maatii Mandi",
      nameAm: "የተቅዋ ልዩ የቤተሰብ ማንዲ",
      descriptionEn: "Feast of smoke-baked seasoned rice served with a massive double shoulder of fork-tender lamb, flame roasted nuts, and hot salsa dip.",
      descriptionAr: "وليمة فاخرة من أرز المندي المدخن المطبوخ برعاية، تقدم مع كتف مزدوج ضخم لحم ضأن شديد الليونة ومزين بالمكسرات المحمصة وصلصة حارة.",
      descriptionOm: "Mandi guddaa foon hoolaa baay'ee lallaafaa, maatii guutuuf kan dhiyaatu.",
      descriptionAm: "ለትልቅ ቤተሰብ ወይም ግብዣ የሚሆን፣ እጅግ በጣም በሚያምር ሁኔታ የተጠበሰ የበግ ስጋና የላቀ የቁም ማንዲ።",
      price: 3800,
      categoryId: "special-mandi",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
      isAvailable: true,
      isFeatured: true
    },
    {
      id: "prod-of-1",
      nameEn: "Charred Flame-Grilled Lamb Ribs",
      nameAr: "أضلاع لحم ضأن مشوية على الفحم",
      nameOm: "Ribs Lamb Grilled",
      nameAm: "የበግ ጎድን ጥብስ",
      descriptionEn: "Succulent free-range lamb ribs marinated in wild mountain honey and aromatic rosemary, charred on open embers.",
      descriptionAr: "أضلاع ضأن مشوية متبلة بعسل الجبل البري وإكليل الجبل العطري، مطهوة على الفحم المتوهج بتجانس تام.",
      descriptionOm: "Ribs hoolaa mimmigaa fi damma gaaraatiin gilaalame.",
      descriptionAm: "በማርና በሮዝመሪ ቅጠል የተቀመመ፣ በእሳት ነበልባል ላይ በልዩ ጥበብ የተጠበሰ ጣፋጭ የበግ ጎድን።",
      price: 1550,
      categoryId: "other-foods",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
      isAvailable: true,
      isFeatured: true
    }
  ],
  hero: {
    titleEn: "Splendor of Hospitality & Traditional Craft",
    titleAr: "روعة الضيافة وفخامة الطهي الأصيل",
    titleOm: "Aadaa fi Kabajaa Keessummeessaa",
    titleAm: "የአስተናጋጅነት ክብርና ባህላዊ አዘገጃጀት",
    subtitleEn: "Indulge in a beautiful union of culinary majesty and heart-warming traditional local tastes in Shashemene. Every ingredient is hand-picked, cooked slow with absolute respect.",
    subtitleAr: "استمتع بمزيج رائع يجمع بين روعة عالم الطهي المتميز والجمال الدافئ للنكهات التقليدية الأصيلة في شاشامان. كل مكون مختار بعناية ومطهو ببطء.",
    subtitleOm: "Magaalaa bareeddii Shashamanee keessatti dhandhama nyaata addaa fi keessummeessaa mi'aawaa fidaa. Nyaatni keenya hunduu jaalalaان qophaaye.",
    subtitleAm: "በውቧ ሻሸመኔ ከተማ ውስጥ የምግብ አዘገጃጀት ጥበብንና ባህላዊ ጣዕምን ያጣጥሙ። እያንዳንዱ ምግብ በፍቅርና በጥንቃቄ የተዘጋጀ ነው።",
    images: [
      "https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=1600",
      "https://images.unsplash.com/photo-1590075865003-e48277faa558?w=1600",
      "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1600"
    ]
  },
  restaurant: {
    nameEn: "Taqwa Restaurant",
    nameAr: "مطعم تقوى",
    nameOm: "Nyaata Taqwa",
    nameAm: "ተቅዋ ሬስቶራንት",
    phone: "+251 91 123 4567",
    email: "hospitality@taqwafood.com",
    addressEn: "Main Street, Area 01, Shashemene, Oromia, Ethiopia",
    addressAr: "الشارع الرئيسي، حي ٢، شاشامان، أوروميا، إثيوبيا",
    addressOm: "Karaa Guddaa, Kutaa 01, Shashamanee, Oromiyaa, Itoophiyaa",
    addressAm: "ዋናው መንገድ፣ ቀበሌ 01፣ ሻሸመኔ፣ ኦሮሚያ፣ እትዮጵያ",
    openingHoursEn: "Daily from 11:30 AM to 11:30 PM",
    openingHoursAr: "يومياً من الساعة ١١:٣٠ صباحاً حتى ١١:٣٠ مساءً",
    openingHoursOm: "Guyyaa guyyaatti sa'aatii 11:30 AM hanga 11:30 PM",
    openingHoursAm: "በየቀኑ ከጠዋቱ 5፡30 እስከ ምሽቱ 5፡30",
    instagramUrl: "https://instagram.com/taqwa_restaurant",
    facebookUrl: "https://facebook.com/taqwafood",
    twitterUrl: "https://twitter.com/taqwafood"
  }
};
